#ifndef GUARD_CONSTANTS_BERRY_H
#define GUARD_CONSTANTS_BERRY_H

#define BERRY_NONE 0

#define BERRY_FIRMNESS_UNKNOWN     0
#define BERRY_FIRMNESS_VERY_SOFT   1
#define BERRY_FIRMNESS_SOFT        2
#define BERRY_FIRMNESS_HARD        3
#define BERRY_FIRMNESS_VERY_HARD   4
#define BERRY_FIRMNESS_SUPER_HARD  5

#define BERRY_COLOR_RED    0
#define BERRY_COLOR_BLUE   1
#define BERRY_COLOR_PURPLE 2
#define BERRY_COLOR_GREEN  3
#define BERRY_COLOR_YELLOW 4
#define BERRY_COLOR_PINK   5

#define FLAVOR_SPICY   0
#define FLAVOR_DRY     1
#define FLAVOR_SWEET   2
#define FLAVOR_BITTER  3
#define FLAVOR_SOUR    4
#define FLAVOR_COUNT   5

#define BERRY_STAGE_NO_BERRY    0  // there is no tree planted and the soil is completely flat.
#define BERRY_STAGE_PLANTED     1
#define BERRY_STAGE_SPROUTED    2
#define BERRY_STAGE_TALLER      3
#define BERRY_STAGE_FLOWERING   4
#define BERRY_STAGE_BERRIES     5
#define BERRY_STAGE_TRUNK       6 // These follow BERRY_STAGE_BERRIES to preserve save compatibility
#define BERRY_STAGE_BUDDING     7
#define BERRY_STAGE_SPARKLING   255

// Berries can be watered in the following stages:
// - BERRY_STAGE_PLANTED
// - BERRY_STAGE_SPROUTED
// - BERRY_STAGE_TALLER
// - BERRY_STAGE_FLOWERING
#define NUM_WATER_STAGES 4

// IDs for berry tree objects, indexes into berryTrees in SaveBlock1
// Named for whatever berry is initially planted there on a new game
// Those with no initial berry are named "soil"
#define BERRY_TREE_ROUTE_102_ORAN    1
#define BERRY_TREE_ROUTE_102_PECHA   2
#define BERRY_TREE_ROUTE_103_ORAN    3
#define BERRY_TREE_ROUTE_103_CHERI   4
#define BERRY_TREE_ROUTE_103_CHESTO  5
#define BERRY_TREE_ROUTE_104_ORAN_1    6
#define BERRY_TREE_ROUTE_104_CHERI  7
#define BERRY_TREE_ROUTE_104_PECHA  8
#define BERRY_TREE_ROUTE_104_ORAN_2   9
#define BERRY_TREE_ROUTE_104_RAWST    10
#define BERRY_TREE_ROUTE_104_PERSIM   11
#define BERRY_TREE_ROUTE_104_ASPEAR   12
#define BERRY_TREE_ROUTE_104_ORAN_3    13
#define BERRY_TREE_ROUTE_123_STARF 14
#define BERRY_TREE_ROUTE_123_AGUAV  15
#define BERRY_TREE_ROUTE_110_LIECHI  16
#define BERRY_TREE_ROUTE_110_PETAYA  17
#define BERRY_TREE_ROUTE_110_SALAC  18
#define BERRY_TREE_ROUTE_111_RABUTA   19
#define BERRY_TREE_ROUTE_111_NOMEL   20
#define BERRY_TREE_ROUTE_112_WATMEL  21
#define BERRY_TREE_ROUTE_112_DURIN  22
#define BERRY_TREE_ROUTE_112_BELUE  23
#define BERRY_TREE_ROUTE_112_SITRUS  24
#define BERRY_TREE_ROUTE_116_CHESTO  25
#define BERRY_TREE_ROUTE_116_RAWST 26
#define BERRY_TREE_ROUTE_117_LUM 27
#define BERRY_TREE_ROUTE_117_ROWAP 28
#define BERRY_TREE_ROUTE_117_JABOCA 29
#define BERRY_TREE_ROUTE_123_LUM_2  30
#define BERRY_TREE_ROUTE_118_COLBUR 31
#define BERRY_TREE_ROUTE_118_HABAN     32
#define BERRY_TREE_ROUTE_118_ROSELI 33
#define BERRY_TREE_ROUTE_119_CHOPLE  34
#define BERRY_TREE_ROUTE_119_COBA  35
#define BERRY_TREE_ROUTE_119_WACAN  36
#define BERRY_TREE_ROUTE_120_KASIB 37
#define BERRY_TREE_ROUTE_120_LUM_2 38
#define BERRY_TREE_ROUTE_120_BABIRI 39
#define BERRY_TREE_ROUTE_120_PAYAPA  40
#define BERRY_TREE_ROUTE_120_SITRUS_1  41
#define BERRY_TREE_ROUTE_120_KEBIA  42
#define BERRY_TREE_ROUTE_120_LUM_1     43
#define BERRY_TREE_ROUTE_120_TANGA    44
#define BERRY_TREE_ROUTE_120_SITRUS_2    45
#define BERRY_TREE_ROUTE_120_CHARTI   46
#define BERRY_TREE_ROUTE_121_CHILAN   47
#define BERRY_TREE_ROUTE_121_RINDO   48
#define BERRY_TREE_ROUTE_121_OCCA    49
#define BERRY_TREE_ROUTE_121_PASSHO   50
#define BERRY_TREE_ROUTE_121_SITRUS_1   51
#define BERRY_TREE_ROUTE_121_SITRUS_2  52
#define BERRY_TREE_ROUTE_121_LUM  53
#define BERRY_TREE_ROUTE_121_CUSTAP   54
#define BERRY_TREE_ROUTE_115_RAZZ   55
#define BERRY_TREE_ROUTE_115_BLUK   56
#define BERRY_TREE_UNUSED             57
#define BERRY_TREE_ROUTE_123_FIGY  58
#define BERRY_TREE_ROUTE_123_KEE  59
#define BERRY_TREE_ROUTE_123_WIKI  60
#define BERRY_TREE_ROUTE_123_MARANGA  61
#define BERRY_TREE_ROUTE_123_LANSAT  62
#define BERRY_TREE_ROUTE_123_MICLE     63
#define BERRY_TREE_ROUTE_123_SITRUS_3  64
#define BERRY_TREE_ROUTE_123_IAPAPA  65
#define BERRY_TREE_ROUTE_116_ASPEAR 66
#define BERRY_TREE_ROUTE_116_PERSIM  67
#define BERRY_TREE_ROUTE_114_TAMATO 68
#define BERRY_TREE_ROUTE_115_NANAB 69
#define BERRY_TREE_ROUTE_115_WEPEAR 70
#define BERRY_TREE_ROUTE_115_PINAP 71
#define BERRY_TREE_UNUSED_2  72
#define BERRY_TREE_ROUTE_123_APICOT 73
#define BERRY_TREE_ROUTE_123_GANLON 74
#define BERRY_TREE_ROUTE_104_SOIL_4   75
#define BERRY_TREE_ROUTE_104_CHERI_2  76
#define BERRY_TREE_ROUTE_114_CORNN 77
#define BERRY_TREE_ROUTE_114_MAGOST 78
#define BERRY_TREE_ROUTE_123_MAGO 79
#define BERRY_TREE_ROUTE_111_SPELON   80
#define BERRY_TREE_ROUTE_111_PAMTRE   81
#define BERRY_TREE_ROUTE_130_LIECHI   82
#define BERRY_TREE_ROUTE_119_YACHE 83
#define BERRY_TREE_ROUTE_119_SHUCA 84
#define BERRY_TREE_ROUTE_119_SITRUS_1   85
#define BERRY_TREE_ROUTE_119_LUM_1    86
#define BERRY_TREE_ROUTE_123_SITRUS_1    87
#define BERRY_TREE_ROUTE_123_SITRUS_2   88
#define BERRY_TREE_ROUTE_123_LUM_1    89
#define BERRY_TREE_ROUTE_104_LEPPA_1  90
#define BERRY_TREE_ROUTE_104_LEPPA_2  91
#define BERRY_TREE_ROUTE_115_POMEG    92
#define BERRY_TREE_ROUTE_115_KELPSY   93
#define BERRY_TREE_ROUTE_115_QUALOT   94
#define BERRY_TREE_ROUTE_115_HONDEW   95
#define BERRY_TREE_ROUTE_115_GREPA    96
#define BERRY_TREE_ROUTE_119_SITRUS_2 97
#define BERRY_TREE_ROUTE_119_SITRUS_3 98
#define BERRY_TREE_ROUTE_119_LUM_2    99
#define BERRY_TREE_ROUTE_119_LUM_3    100

// Remainder are unused

#define BERRY_TREES_COUNT 128

#endif // GUARD_CONSTANTS_BERRY_H
