#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(ACROBATICS) \
    F(AERIAL_ACE) \
    F(AFTER_YOU) \
    F(AIR_SLASH) \
    F(AURA_SPHERE) \
    F(AURORA_VEIL) \
    F(BLIZZARD) \
    F(BODY_PRESS) \
    F(BREAKING_SWIPE) \
    F(BUG_BUZZ) \
    F(BULLDOZE) \
    F(BULLET_SEED) \
    F(CHILLING_WATER) \
    F(DARK_PULSE) \
    F(DAZZLING_GLEAM) \
    F(DEFOG) \
    F(DIG) \
    F(DRAGON_CLAW) \
    F(DRAGON_PULSE) \
    F(DRAIN_PUNCH) \
    F(DRAINING_KISS) \
    F(DUAL_WINGBEAT) \
    F(EARTH_POWER) \
    F(EARTHQUAKE) \
    F(ELECTROWEB) \
    F(ENERGY_BALL) \
    F(EXPLOSION) \
    F(FACADE) \
    F(FAKE_TEARS) \
    F(FEATHER_DANCE) \
    F(FEINT_ATTACK) \
    F(FLAMETHROWER) \
    F(FLASH_CANNON) \
    F(FLIP_TURN)\
    F(FOCUS_PUNCH) \
    F(GIGA_DRAIN) \
    F(GRASS_KNOT) \
    F(GRAVITY) \
    F(HEAT_CRASH) \
    F(HEAVY_SLAM) \
    F(HURRICANE) \
    F(HYPER_VOICE) \
    F(ICE_BEAM) \
    F(ICICLE_SPEAR) \
    F(ICY_WIND) \
    F(IRON_HEAD) \
    F(LEECH_LIFE) \
    F(LIGHT_SCREEN) \
    F(LOW_KICK) \
    F(LOW_SWEEP) \
    F(MAGICAL_LEAF) \
    F(ME_FIRST) \
    F(MISTY_EXPLOSION) \
    F(MUD_SHOT) \
    F(NIGHT_SHADE) \
    F(PARTING_SHOT) \
    F(PAYBACK) \
    F(PIN_MISSILE)\
    F(PLAY_ROUGH) \
    F(POISON_JAB) \
    F(POUNCE) \
    F(POWER_GEM) \
    F(PROTECT) \
    F(PSYCHIC) \
    F(PSYCHIC_FANGS) \
    F(REFLECT) \
    F(ROCK_BLAST) \
    F(ROCK_SLIDE) \
    F(ROCK_TOMB) \
    F(ROOST) \
    F(SCALE_SHOT) \
    F(SCARY_FACE) \
    F(SCREECH) \
    F(SEED_BOMB) \
    F(SEISMIC_TOSS) \
    F(SHADOW_BALL) \
    F(SHADOW_PUNCH) \
    F(SHOCK_WAVE) \
    F(SKILL_SWAP) \
    F(SLUDGE_BOMB) \
    F(SMART_STRIKE) \
    F(SNARL) \
    F(SOLAR_BEAM) \
    F(SOLAR_BLADE) \
    F(STRUGGLE_BUG) \
    F(SUPERCELL_SLAM) \
    F(SWIFT) \
    F(TAILWIND) \
    F(TELEPORT) \
    F(THROAT_CHOP)\
    F(THUNDER) \
    F(THUNDER_WAVE) \
    F(THUNDERBOLT) \
    F(TOXIC) \
    F(TRIPLE_AXEL) \
    F(U_TURN)\
    F(VOLT_SWITCH)\
    F(WEATHER_BALL) \
    F(WILL_O_WISP) \
    F(X_SCISSOR) 

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
