# 1 "data/maps/SpiralCity_House2/scripts.pory"

# 2 "data/maps/SpiralCity_House2/scripts.pory"
SpiralCity_House2_MapScripts::
# 3 "data/maps/SpiralCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/SpiralCity_House2/scripts.pory"

# 5 "data/maps/SpiralCity_House2/scripts.pory"
RustboroCity_House2_EventScript_PokefanF::
# 6 "data/maps/SpiralCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
# 7 "data/maps/SpiralCity_House2/scripts.pory"
	end
# 8 "data/maps/SpiralCity_House2/scripts.pory"

# 9 "data/maps/SpiralCity_House2/scripts.pory"
RustboroCity_House2_EventScript_LittleGirl::
# 10 "data/maps/SpiralCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
# 11 "data/maps/SpiralCity_House2/scripts.pory"
	end
# 12 "data/maps/SpiralCity_House2/scripts.pory"

# 13 "data/maps/SpiralCity_House2/scripts.pory"
RustboroCity_House2_Text_TrainerSchoolExcellent:
# 14 "data/maps/SpiralCity_House2/scripts.pory"
	.string "The TRAINER'S SCHOOL is excellent.\p"
# 15 "data/maps/SpiralCity_House2/scripts.pory"
	.string "If you study there, you could even\n"
# 16 "data/maps/SpiralCity_House2/scripts.pory"
	.string "become a GYM LEADER.$"
# 17 "data/maps/SpiralCity_House2/scripts.pory"

# 18 "data/maps/SpiralCity_House2/scripts.pory"
RustboroCity_House2_Text_RoxanneKnowsALot:
# 19 "data/maps/SpiralCity_House2/scripts.pory"
	.string "ROXANNE, the GYM LEADER, really knows\n"
# 20 "data/maps/SpiralCity_House2/scripts.pory"
	.string "a lot about POKéMON.\p"
# 21 "data/maps/SpiralCity_House2/scripts.pory"
	.string "She's really strong, too!$"
