OldaleTown_House1_EventScript_PokeballChanger::
# 2 "data/maps/OldaleTown_House1/scripts.pory"
	lock
# 3 "data/maps/OldaleTown_House1/scripts.pory"
	faceplayer
# 4 "data/maps/OldaleTown_House1/scripts.pory"
	msgbox OldaleTown_House1_EventScript_PokeballChanger_Text_0
# 5 "data/maps/OldaleTown_House1/scripts.pory"
	release
	end


# 9 "data/maps/OldaleTown_House1/scripts.pory"

# 10 "data/maps/OldaleTown_House1/scripts.pory"

# 11 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_MapScripts::
# 12 "data/maps/OldaleTown_House1/scripts.pory"
	.byte 0
# 13 "data/maps/OldaleTown_House1/scripts.pory"

# 14 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_EventScript_Woman::
# 15 "data/maps/OldaleTown_House1/scripts.pory"
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
# 16 "data/maps/OldaleTown_House1/scripts.pory"
	end
# 17 "data/maps/OldaleTown_House1/scripts.pory"

# 18 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
# 19 "data/maps/OldaleTown_House1/scripts.pory"
	.string "When a Pokémon battle starts, the one\n"
# 20 "data/maps/OldaleTown_House1/scripts.pory"
	.string "at the left of the list goes out first.\p"
# 21 "data/maps/OldaleTown_House1/scripts.pory"
	.string "So, when you get more Pokémon in your\n"
# 22 "data/maps/OldaleTown_House1/scripts.pory"
	.string "party, try switching around the order\l"
# 23 "data/maps/OldaleTown_House1/scripts.pory"
	.string "of your Pokémon.\p"
# 24 "data/maps/OldaleTown_House1/scripts.pory"
	.string "It could give you an advantage.$"

OldaleTown_House1_EventScript_PokeballChanger_Text_0:
# 4 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Placeholder for Pokéball changing NPC.$"
