enum FeaturesMenu
{
    FEATURES_MENU_PORTA_PC,
    FEATURES_MENU_POKE_VIAL,
    FEATURES_MENU_REPEL,
    FEATURES_MENU_MOVE_TUTORS,
    FEATURES_MENU_POKE_RIDER,
    FEATURES_MENU_HEART_SCALES,
    FEATURES_MENU_MOVE_DELETER,
    FEATURES_MENU_BADGE_BOOST,
};

enum HeartScalesMenu
{
    HEART_SCALE_MENU_MOVE_REMINDER,
    HEART_SCALE_MENU_CHANGE_IV,
    HEART_SCALE_MENU_CHANGE_NATURE,
    HEART_SCALE_MENU_CHANGE_ABILITY,
    HEART_SCALE_MENU_INCREASE_LEVEL_CAP,
}

enum HeartScalesIvMenu
{
    IV_MENU_HP,
    IV_MENU_ATTACK,
    IV_MENU_DEFENSE,
    IV_MENU_SPECIAL_ATTACK,
    IV_MENU_SPECIAL_DEFENSE,
    IV_MENU_SPEED,
}

enum HeartScalesNatureMenu
{
    NATURE_MENU_HARDY,
    NATURE_MENU_LAX,
    NATURE_MENU_GENTLE,
    NATURE_MENU_BRAVE,
    NATURE_MENU_BOLD,
    NATURE_MENU_RELAXED,
    NATURE_MENU_IMPISH,
    NATURE_MENU_QUIET,
    NATURE_MENU_CALM,
    NATURE_MENU_SASSY,
    NATURE_MENU_CAREFUL,
    NATURE_MENU_LONELY,
    NATURE_MENU_ADAMANT,
    NATURE_MENU_NAUGHTY,
    NATURE_MENU_TIMID,
    NATURE_MENU_HASTY,
    NATURE_MENU_JOLLY,
    NATURE_MENU_NAIVE,
    NATURE_MENU_MODEST,
    NATURE_MENU_MILD,
    NATURE_MENU_RASH,
}